### ISSUE TITLE
Tagging (phase-III) lets center environment into minipage

### ISSUE THREAD

**Issue by John02139** [latex3/tagging-project#119]
I encountered the following with a verbatim environment inside a centered minipage. Without tagging, the minipage is centered, but the verbatim content inside the minipage is not centered (as desired).  With tagging, the verbatim material is centered. 

```
\DocumentMetadata 
{
	pdfstandard = a-4f,
	pdfversion  = 2.0,
	lang		= en-US,
	testphase = {phase-III}, % <==== with testphase, the verbatim code becomes centered.
}
\documentclass[11pt]{article}

\newcommand*{\Sphinx}{I won't say. }

\begin{document}

\begin{center}
\begin{minipage}{0.8\textwidth}
\begin{verbatim}

\Sphinx\Sphinx\Sphinx\Sphinx\Sphinx\Sphinx\Sphinx
\Sphinx\Sphinx\Sphinx\Sphinx\Sphinx
\Sphinx\Sphinx\Sphinx

\end{verbatim}
\end{minipage}
\end{center}

\end{document}  
```

**Comment by u-fischer** [comment]
Well it is not the minipage. You get similar problems without it. The problem is that the display environments do not reset the para-instance. That means they inherit from the center environment.   You can change that with the optional argument

~~~~
\begin{verbatim}[para-instance=justify]
~~~~

Generally, in standard LaTeX a list resets parts of the values, e.g. the leftskip is always 0pt. But it doesn't look very consistent, e.g. a `\raggedleft` outside gives a `\raggedright` inside the list, so I'm not sure if that is by design ...

~~~~
\documentclass[11pt]{article}

\usepackage{lipsum}
\begin{document}

\lipsum[1][1-4]
\begin{center}
\begin{itemize}
\item \lipsum[1][1-4]
\end{itemize}
\end{center}

\raggedright
\lipsum[1][1-4]
\begin{center}
\begin{itemize}
\item \lipsum[1][1-4]
\end{itemize}
\end{center}

\raggedleft
\lipsum[1][1-4]
\begin{center}
\begin{itemize}
\item \lipsum[1][1-4]
\end{itemize}
\end{center}

\end{document}
~~~~

![image](https://github.com/user-attachments/assets/8b64ddb2-eb92-4fd4-b2ca-c22e594ca504)

With the block code one could reset the para-instance:

~~~~
\DocumentMetadata 
{
	pdfstandard = a-4f,
	pdfversion  = 2.0,
	lang		= en-US,
	testphase = {block}, % 
}
\documentclass[11pt]{article}

\usepackage{lipsum}
\begin{document}
\RenewDocumentEnvironment{itemize}{!O{}}
    { \UseInstance{blockenv}{itemize} {para-instance=justify,#1} } %<-----------
    { \endblockenv }

\lipsum[1][1-4]
\begin{center}
\begin{itemize}
\item \lipsum[1][1-4]
\end{itemize}
\end{center}

\raggedright
\lipsum[1][1-4]
\begin{center}
\begin{itemize}
\item \lipsum[1][1-4]
\end{itemize}
\end{center}

\raggedleft
\lipsum[1][1-4]
\begin{center}
\begin{itemize}
\item \lipsum[1][1-4]
\end{itemize}
\end{center}

\end{document}
~~~~

This gives always justified paragraphs inside the list. But I couldn't setup a para-instance that reproduce the standard latex setup and I'm not sure what we really want here.

**Comment by FrankMittelbach** [comment]
I think the expectation is that verbatim is verbatim, thus in  an LR document it should always be left aligned. One can argue about whether or not other lists should inherit values or not, but for verbatim I think it is simply a bug.
```
\EditInstance{blockenv}{verbatim}{ para-instance=justify } 

```
fixes that, but I think it should be set this way in latex-lab-block already.

**Comment by u-fischer** [comment]
For verbatim this is fixed in develop. For other lists this is now referenced in #546

**Comment by John02139** [comment]
Confirming fixed in dev and closing.
