### ISSUE TITLE
\addcontentsline produces warning when used in isolation

### ISSUE THREAD

**Issue by John02139** [latex3/tagging-project#20]
```
\DocumentMetadata{ 
	testphase = {phase-III},
}
\documentclass[12pt]{report} 
\usepackage{hyperref}

% Some special page for the front matter
\newcommand*\SpecialPage{%
	{\Huge\textbf{Special Page}}%
	\addcontentsline{toc}{chapter}{\textbf{Special Page}}%
	\newpage
}

\begin{document}

\SpecialPage
\tableofcontents

\chapter{One}
\section{Intro}
This text introduces our subject.
\end{document}
```
% \addcontentsline causes the following warning:

```
%  Package tagpdf Warning: Destination section*.1 has no related structure.
%  (tagpdf)                /Ref for structure 11 not updated

```

**Comment by FrankMittelbach** [comment]
Well, the problem is that this first page does indeed has no structure it is just a `<p>` essentially and there is no structure with an anchor that the TOC could jump to and `\addcontentsline{toc}{chapter}...` tells it to jump to some chapter structure.

Basically, you tell the toc "format me a line that looks as if there is a chapter", which works fine if you only print, but if you try to produce a structured pdf it rightly tells you "but there is no chapter to point to".

If you use `\chapter*{Special Page}` instead it comes out fine.

**Comment by John02139** [comment]
Thanks very much.  I understand your response!

I did notice that \chapter*{..} is a good solution for pages that will have chapter-like layout (Preface, Foreword, etc), but I'm also working with pages that have a very different [prescribed] design (for which \chapter* is unacceptable). Is there tool for adding appropriate structure to a these "special pages", which need to enter the TOC (and bookmarks) as if they are chapters?   Apologies if this I'm asking the wrong question in the wrong place!

**Comment by FrankMittelbach** [comment]
Hi John. Yes I understand that requests very well too and yes there will be ways (not sure how far that is exposed already to be honest) given that what `\chapter*` does can be done also in directly. I wouldn't be surprised if @u-fischer is going to write a much more comprehensive answer.

**Comment by u-fischer** [comment]
Currently the connection between a destination name and a structure is more or less only established and stored if a `\refstepcounter` is issued. This will be extended later (\addcontentsline will perhaps have to write an additional line or an extended argument to pass also the structure number to the toc). For now you can get around the problem by using an arbitrary `\refstepcounter` of some dummy counter. You should also start the paragraph first, so that you are in the right structure.

~~~~
\DocumentMetadata{ 
        testphase = {phase-III},
}
\documentclass[12pt]{report} 
\usepackage{hyperref}
\newcounter{dummy}
% Some special page for the front matter
\newcommand*\SpecialPage{%
        \noindent\refstepcounter{dummy}{\Huge\textbf{Special Page}}%
        \addcontentsline{toc}{chapter}{\textbf{Special Page}}%
        \newpage
}

\begin{document}

\SpecialPage 

\tableofcontents 

\chapter{One}
\section{Intro}
This text introduces our subject.
\end{document}
~~~~

**Comment by John02139** [comment]
Thank you both!  I will implement this very simple fix in the document I'm managing.

**Comment by u-fischer** [comment]
It is more a work-around than a fix.  You need a target for the link, but it should be possible to set it also manually and not only through a  \refstepcounter.

**Comment by FrankMittelbach** [comment]
or even a hack :-) anyway nothing that you should plan on coninuing for long. So watch the development (and if we don't forget we'll update this pr once there is a proper solution available.

**Comment by John02139** [comment]
:-)  No worries for a hack - my institution has a long tradition of "hacking", in its broadest sense.  But I'll follow carefully developments on this and the other tagging issues as they come along.

**Comment by u-fischer** [comment]
With an up-to-date system you should be able to set a target with

~~~~
\MakeLinkTarget*{specialpage}{\Huge\textbf{Special Page}}
~~~~

**Comment by John02139** [comment]
I confirm that this works (and does not throw errors when `\DocumentMetadata` isn't loaded).  No further need for a manual `\refstepcounter`!
