### ISSUE TITLE
tabular* + \extracolsep{\fill} produces crash with testphase = {phase-III,tabular,math}

### ISSUE THREAD

**Issue by John02139** [latex3/tagging-project#25]
With \tabular*, adding "math" to testphase leads to a crash IF \extracolsep{\fill} is included.
```
\DocumentMetadata{ 
	testphase = {phase-III,tabular,math},
}
\documentclass[12pt]{report} 
\begin{document}

\begin{tabular*}{0.2\textwidth}{@{\extracolsep{\fill}}cc}
\hline
AA & BB \\
CC & DD \\
\hline
\end{tabular*}
\end{document}
```
yields the following
```
 Runaway argument?
 \col@sep \tabcolsep \let \d@llarbegin \begingroup \let \d@llarend \endgroup \ETC.
 ! File ended while scanning use of \__math_grab_dollar:w.
 <inserted text> 
                \par 
 <*> tabular.tex
               
 ?
```

**Comment by u-fischer** [comment]
The problem is not with \extracolsep, even without it the behaviour is wrong: the code tries to collect the tabular* as a math formula which is wrong and with \extracolsep it explodes.  
The math module contains code for *places where math mode is (ab)used* but this only handles tabular, tabular* has been forgotten. You can add it for now like this:

~~~~
\DocumentMetadata{ 
        testphase = {phase-III,tabular,math},
}
\documentclass[12pt]{report} 
\ExplSyntaxOn
\AddToHook{ env/ tabular*/begin }
      { \bool_set_true:N \l__math_collected_bool }
\ExplSyntaxOff

\begin{document}
     
\begin{tabular*}{0.2\textwidth}{@{\extracolsep{\fill}}cc}
\hline
AA & BB \\
CC & DD \\
\hline
\end{tabular*}
\end{document}
~~~~

**Comment by John02139** [comment]
Thanks again, confirming that this fixes the issue I saw.

**Comment by John02139** [comment]
This is fixed in the PdfLaTeX-dev release.

LaTeX2e <2024-06-01> pre-release-2 (develop 2024-5-13 branch)
L3 programming layer <2024-05-08>
