### ISSUE TITLE
with \(...\) math processor is applied twice

### ISSUE THREAD

**Issue by u-fischer** [latex3/tagging-project#29]
As `\(..\)` internally calls `$...$` the math processor is currently applied twice:
 
~~~~
\DocumentMetadata{testphase=math} 
\documentclass{article}
\ExplSyntaxOn
\math_processor:n{\typeout{Math!}}
\ExplSyntaxOff

\begin{document}
\( a=b \) 
\end{document} 
~~~~

gives

~~~~
Math!
Math!
====>first-result=macro:->a=b
====>first-tmpmathcontent=macro:->
====>formula has no subparts
~~~~

**Comment by car222222** [comment]
The treatment of \( is a bit of mess, since so many people have fiddled with it.

Thus much of it needs fixing, including dealing with edge cases.

Best to wait for a full, and very clear, specification of everything related to math in latex-lab, as requested elsewhere (many times, by now), rather than fiddling with odd bits of it every few weeks.

**Comment by car222222** [comment]
The treatment of \( is a bit of mess, since so many people have fiddled with it.

Thus much of it needs fixing, including dealing with edge cases.

Best to wait for a full, and very clear, specification of everything related to math in latex-lab, as requested elsewhere (many times, by now), rather than fiddling with odd bits of it every few weeks.
