### ISSUE TITLE
ethiop package incompatible

### ISSUE THREAD

**Issue by mbertucci47** [latex3/tagging-project#656]
The [ethiop](https://ctan.org/pkg/ethiop) package errors with the tagging code loaded. The example
```tex
\DocumentMetadata
  {
    lang=en-US,
    pdfversion=2.0,
    pdfstandard=ua-2,
    testphase={phase-III,math,title,table,firstaid}
  }
\documentclass{article}
\usepackage[english]{babel}
\usepackage{ethiop}

\title{ethiop tagging test}

\begin{document}

\selectlanguage{english}'adis 'ababA

\selectlanguage{ethiop}'adis 'ababA

\end{document}
```
errors with
```
! LaTeX hooks Error: Generic hooks cannot be added to '\refstepcounter'.
```
It does not error without the tagging code.

I doubt many people are using this package, but it is in tlc3.

**Comment by u-fischer** [comment]
imho the same problem as #414

**Comment by car222222** [comment]
The important question concerning such packages is: 
     How much is it used by those who do (need to) use it!
Not:
     How little is it used by those who do not need to use it, 
since such non-users tell us nothing about its true, overall importance.  
﻿
More  specifically:

>  I doubt many people are using this package 
Why do you doubt its usage level being higher?  
Note that I am not claiming you are wrong! 

More generally:

This package (as are all language-based packages) is of course, a very nice example of how important it is not to neglect any such specialised packages and classes just on account of their having low usage. 
Every language-related package is hugely important, however uncommon that language may be!  

Even if the number of people who will ever use a class or package will always remain relatively small, it does not follow that that one is low priority: this is because it may 
be essential to the 20 people in the universe who write about that subject area.  
And that subject area itself may be of supreme importance to 90% of the population of that universe, however few people actually need to write to each other about it! 

A package or class may be used only by a small group, but it is  very probably vital 
for that group to be able to write anything: they absolutely must use it because there 
is nothing else they can do (TINA). 

There are also other similar subcategories with examples that may be deemed
 “little used” and therefore get misleadingly labelled as “not important” or 
“low priority” — for example:
many institutional cases of classes that are required for use by an single institution,
or publisher, or publication, etc.;  
specialised applications (whether or not this specialisation affects the formatting requirements).
 
Note that in such situations, the usage is never optional since each is essential 
for a (possibly very small) group of users. 

Whilst It would indeed be useful to note, somewhere, that files in these distinct 
 categories may well be very little used,  but please also record how vital they are (and also, if known, describe to whom they are so vital).  
They should not be simply dropped and forgotten! Please!! 

It would be best for us to categorise usage not by total number of uses, but rather 
by the importance of its use to those who ever need to use it it at all, whilst ignoring those who would never use it however important it is!

**Comment by mbertucci47** [comment]
@car222222 I agree with you. My doubt that many people use ethiop is due to their now being much easier ways to input Amharic (and other non-latin scripts) directly to be used with a Unicode engine

**Comment by car222222** [comment]
Understood, @mbertucci47 for the extra information. 

I had not even heard of ethiopic before this!
