### ISSUE TITLE
no information about conformity with any standard

### ISSUE THREAD

**Issue by hpvd** [latex3/tagging-project#724]
Building a minimal example following this guide
https://latex3.github.io/tagging-project/documentation/prototype-usage-instructions.html

acrobat reader shows this message:
`The currently displayed PDF document does not contain any information on conformity with any standards.`

would expect to see pdf standard version set in Metadata

code:
```
\DocumentMetadata{
  lang        = de,
  pdfversion  = 2.0,
  pdfstandard = ua-2,
  pdfstandard = a-4f, %or a-4
  testphase   = 
   {phase-III,
    title,
    table,
    math,
    firstaid}  
}

\documentclass{article}

\begin{document}
\section{test section}
test text in section


\end{document}
```

pdf build with latest miktex, using texworks, lualatex on windows 11

![2024-10-03_11h05_30](https://github.com/user-attachments/assets/ee02a30c-b395-49eb-a3ca-2936d4c8d523)

**Comment by u-fischer** [comment]
well it works if you use

~~~~
  pdfversion  = 1.7,
  pdfstandard = ua-1,
  pdfstandard = a-3a, 
~~~~

![image](https://github.com/user-attachments/assets/6991e208-2877-4740-8f92-735d6e5cc63e)

The problem is that adobe reader does not understand PDF 2.0 and the related, newer standards yet. For verapdf the pdf 2.0 file is fine (apart from the fact that the title is missing and so it is not ua-2 compliant.) Open a feature request for adobe ...

**Comment by hpvd** [comment]
this does not change after making the pdf fully passing https://dev.verapdf-rest.duallab.com/
by adding title command to the code

```
\DocumentMetadata{
  lang        = de,
  pdfversion  = 2.0,
  pdfstandard = ua-2,
  pdfstandard = a-4f, %or a-4
  testphase   = 
   {phase-III,
    title,
    table,
    math,
    firstaid}  
}

\documentclass{article}

**\title{test title}**

\begin{document}
\section{test section}
test text in section


\end{document}
```

**Comment by hpvd** [comment]
posting at the same time :-)

**Comment by hpvd** [comment]
hmm acrobat is talking about PDF 2.0 compatibility since 2017...
https://helpx.adobe.com/bg/acrobat/using/whats-new-dc-2017.html
and since 2020 in their sdk
https://opensource.adobe.com/dc-acrobat-sdk-docs/pdflsdk/releasenotes18.html#version-18-0

![2024-10-03_11h54_45](https://github.com/user-attachments/assets/55afc1be-5f48-4cf5-8c20-2ece7feeeeb9)

![2024-10-03_11h49_11](https://github.com/user-attachments/assets/6cac5569-b992-46ff-8c28-0c44d42826cb)

-> possibly incomplete...

**Comment by FrankMittelbach** [comment]
The fact that (at this point) Acrobat doesn't fully understand compliant PDFs when they are PDF 2.0 based, e.g., PDF/UA-2 doesn't make then non-compliant. It would be wrong to suggest going to 1.7 for that reason, because 1.7 doesn't tag math properly and has other defects with respect to accessibility. So it is important to move to PDF/UA-2 especially for documents that are more complex, eg typical STEM docs produced from LaTeX.

If we do want good accessible PDFs we have to push the PDF consumers (eg Acrobat) to properly support the PDF 2.0 based standards instead of continuing to produce 1.7 based ones (except in an emergency) because for users in need of accessible documents, PDF/UA-1 is largely useless and the task shouldn't be to get a checkmark from a defective verification (that somehting complies to a standard) but to get the checker programs do the right thing and use something that is actually helpful for people who need it.

So I'm all for explicitly pointing out that at this point in time many consumer  and checker applications do not yet recognize the standards as necessary, but not to suggest the 1.7 preamble is something to become "compliant".

**Comment by u-fischer** [comment]
@FrankMittelbach I didn't suggest (or make the impression that I suggest) to use pdf 1.7. I only wanted to show that our code correctly set the standard declarations and that it is adobe that doesn't understand that. 

@hpvd Adobe can read PDF 2.0 files without problems, and it supports some of its features (from the list mostly stuff related to printing etc) but sadly not all.

**Comment by hpvd** [comment]
> I didn't suggest (or wanted to make the impression that I suggest) to use pdf 1.7. I only wanted to show that our code correctly set the standard declarations and that it is adobe that doesn't understand that.

I got that right.

**Comment by FrankMittelbach** [comment]
@u-fischer my point was with respect to what  @hpvd suggested "_to give users a fully compatible pdf right from the start?_" 

We do give compliant PDFs from the start so we should point out that this is the case, despite the fact that some defective checkers are unable to recognize the new standards. In addition we can suggest that in order to *fool* defective checkers one can fall back to 1.7 standards, but suggest to do that only if some requirement (like some University using a defective checker) needs a checkmark.

**Comment by hpvd** [comment]
>  @hpvd suggested "_to give users a fully compatible pdf right from the start?_"

this was only about adding the title code line to the usage instructions.

**Comment by FrankMittelbach** [comment]
ok we we all talkedabout different aspects :-) .... I think biggest point is really to have feature requests being made with the vendors if we don't want to see PDFs staying a problem for STEM documents. We can push only so far (by providing good PDF/UA-2 documents, for example) but user pressure might help with that.

**Comment by hpvd** [comment]
for texworks the seems to be also some things to be made compatible to pdf 2.0...
see https://github.com/TeXworks/texworks/issues/1063
@u-fischer can you comfirm that there are changes in the field of metadata inclusion when moving to pdf 2.0?

**Comment by u-fischer** [comment]
yes, I added a comment to the texworks issue.
